server:
  port: 9090

devkit:
  component:
    config:
      system: test-system
      register:
        port: 6379
        host: 127.0.0.1
    task:
      job:
        enabled: true
        pool-size: 5
        thread-name-prefix: "test-task-scheduler-"
        wait-for-tasks-to-complete-on-shutdown: true
        await-termination-seconds: 30
        refresh-interval: 30000
        clean-invalid-tasks-cron: "0 0/5 * * * ?"

logging:
  level:
    root: info
  config: classpath:logback-spring.xml